[package]
name = "rustful-api"
authors = ["hjkl1"]
version = "0.1.0"
edition = "2021"
rust-version = "1.78"
categories = ["RESTful API", "Web"]
repository = "https://github.com/hjklchan/rustful-api"

[dependencies]
